### ISSUE TITLE
Updating Tests in the Care Project

### ISSUE THREAD

**Issue by aeswibon** [ohcnetwork/care#1372]
# Tests in Care

:lock: __Dont assign this issue__

This is an EPIC issue that monitors the progress of improving tests in the `Care Backend Project`

## Problem

The current unit tests in the project have several shortcomings:

- Not all modules are covered by tests.
- Many edge cases are not addressed.

## Solution

To address the issues mentioned above, the following solution is proposed:

- Add tests for every CRUD endpoint by creating various test classes.
- The test classes will inherit from the [`TestBase` class](https://github.com/coronasafe/care/blob/ee6c604392602609730536e8d80e6e4e57bffa35/care/utils/tests/test_base.py#LL29C1-L30C1), which provides a base set of functionalities and utilities for testing.

:page_facing_up: _Note: Currently, the focus will be on creating tests for the API endpoint_

By implementing this solution, we aim to improve the test coverage significantly.

## Tasks

- [x] #1376
- [x] #1377
- [ ] #1378
- [ ] #1379
- [x] #1380
- [x] #1385
- [x] #1386
- [ ] #1387
- [x] #1388
- [ ] #1389
- [ ] Adds test for various endpoints in the `ward`, `local_body`, `district`, and `state` module
- [ ] Adds test for various endpoints in the `external_result` module
- [ ] Adds test for various endpoints in the `facility` module
- [ ] Adds test for various endpoints in the `files` module
- [ ] Adds test for various endpoints in the `investigation` and `icd` module
- [ ] Adds test for various endpoints in the `patient` module
- [ ] Adds test for various endpoints in the `pharmacy` module
- [ ] Adds test for various endpoints in the `resources` module
- [ ] Adds test for various endpoints in the `shift` module
- [ ] Adds test for various endpoints in the `test_sample`, `triage` module
